<?xml version="1.0" encoding="utf-8"?><Database Name="BlogNews" Class="ConnectionDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-NJFFDR2;Initial Catalog=BlogNews;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="BlogNewsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Comment" Member="Comments">
    <Type Name="Comment">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Fullname" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DateCommented" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CommentContent" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="EmailAddress" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NewsId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="New_Comment" Member="New" ThisKey="NewsId" OtherKey="Id" Type="New" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="RoleId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="User_New" Member="News" ThisKey="Id" OtherKey="UserId" Type="New" />
      <Association Name="Role_User" Member="Role" ThisKey="RoleId" OtherKey="Id" Type="Role" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CurrentTypeNews" Member="CurrentTypeNews">
    <Type Name="CurrentTypeNew">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CurrentTypeNewsDescription" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="CurrentTypeNew_TypeNew" Member="TypeNews" ThisKey="Id" OtherKey="CurrentTypeNewsId" Type="TypeNew" />
    </Type>
  </Table>
  <Table Name="dbo.News" Member="News">
    <Type Name="New">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Background" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Header" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Content" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DateSubmited" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CountView" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CountShare" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TypeNewsId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Keyword" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="New_Comment" Member="Comments" ThisKey="Id" OtherKey="NewsId" Type="Comment" />
      <Association Name="User_New" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
      <Association Name="TypeNew_New" Member="TypeNew" ThisKey="TypeNewsId" OtherKey="Id" Type="TypeNew" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Role" Member="Roles">
    <Type Name="Role">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RoleDescription" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Role_User" Member="Users" ThisKey="Id" OtherKey="RoleId" Type="User" />
    </Type>
  </Table>
  <Table Name="dbo.TypeNews" Member="TypeNews">
    <Type Name="TypeNew">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TypeNewsDescription" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CurrentTypeNewsId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TypeNew_New" Member="News" ThisKey="Id" OtherKey="TypeNewsId" Type="New" />
      <Association Name="CurrentTypeNew_TypeNew" Member="CurrentTypeNew" ThisKey="CurrentTypeNewsId" OtherKey="Id" Type="CurrentTypeNew" IsForeignKey="true" />
    </Type>
  </Table>
</Database>